-- ==========================================================================
-- FINANPRO DATABASE SCHEMA (SUPABASE / POSTGRESQL)
-- Ejecuta este script en el SQL Editor de tu proyecto en Supabase.com
-- ==========================================================================

-- 1. Tabla de Transacciones (Ingresos y Gastos)
CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description TEXT NOT NULL,
  amount NUMERIC(12, 2) NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('ingreso', 'gasto')),
  category TEXT NOT NULL,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabla de Metas de Ahorro
CREATE TABLE IF NOT EXISTS goals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  target NUMERIC(12, 2) NOT NULL,
  current NUMERIC(12, 2) NOT NULL DEFAULT 0,
  deadline DATE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabla de Presupuestos por Categoría
CREATE TABLE IF NOT EXISTS budgets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category TEXT UNIQUE NOT NULL,
  amount NUMERIC(12, 2) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================================================
-- POLÍTICAS DE SEGURIDAD (Row Level Security - RLS)
-- Permite lectura y escritura desde la aplicación web
-- ==========================================================================

ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE budgets ENABLE ROW LEVEL SECURITY;

-- Políticas de acceso público (Anon Key)
CREATE POLICY "Permitir todo en transactions" ON transactions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir todo en goals" ON goals FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir todo en budgets" ON budgets FOR ALL USING (true) WITH CHECK (true);

-- Datos iniciales de prueba (Opcional)
INSERT INTO goals (name, target, current, deadline) VALUES
  ('Fondo de Emergencia', 5000, 3400, '2026-12-31'),
  ('Vacaciones Familiares', 2500, 1800, '2026-09-15'),
  ('Portafolio de Inversión', 10000, 4200, '2027-06-30')
ON CONFLICT DO NOTHING;

INSERT INTO budgets (category, amount) VALUES
  ('Vivienda', 1200),
  ('Alimentación', 600),
  ('Transporte', 350),
  ('Servicios', 250),
  ('Entretenimiento', 300),
  ('Inversiones', 500),
  ('Salud', 200)
ON CONFLICT DO NOTHING;
